### ISSUE TITLE
Azure portals don't work anymore

### ISSUE THREAD

**Issue by rgkey9000** [novotnyllc/UseMyCurrentAccount#4] opened 2021-06-12 08:31 UTC
When I navigate to a [AAD Users](https://portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/MsGraphUsers) it prompts all accounts window instead of picking my edge account

**Comment by clairernovotny** [comment] 2021-10-04 13:15
Closing as I can't reproduce. Please re-open with a repro if it still occurs.

**Closed as completed by clairernovotny** 2021-10-04 13:15 UTC
